language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v -race .
